# _config.yml

title: "Awesome StarSorted"
author:
  name: devsjc


# Build
remote_theme: just-the-docs/just-the-docs
markdown: kramdown

plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/devsjc/awesome-starsorted"
    

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true
