name: Test builds successfully with Jeckyll

on:
  push:
    branches: ['main']

jobs:     
  build:
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor }} != "GitHub Action Bot"
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./lists

