name: Generate workflow files

on:
  push:
    branches: ['main']

jobs:     
  build:
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor }} != "GitHub Action Bot"
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Create workflow files for lists in lists.json
        run: |
          chmod u+x gen-workflow.sh
          cat lists.json | jq -r '.lists[] | map(values) | @sh' | while read -r name url schedule; do 
            eval name=$name
            eval url=$url
            [ -e .github/workflows/$name.yaml ] && rm .github/workflows/$name.yml
            bash gen-workflow.sh $name $url "$schedule" > .github/workflows/$name.yml
          done
      - name: Commit generated workflow
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .github/workflows/*.yml
          git commit -m "Generate workflow yaml [skip ci]"
          git push origin main  


