name: Generate workflow files

on:
  push:
    branches: ['main']

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Create workflow files for lists in lists.json
        run: |
          for row in $(cat lists.json | jq -r '.[] | map(["list-name"], ["list-url"], .schedule) | @sh')
          do
            echo $1 $2 $3
          done
