name: Generate workflow files

on:
  push:
    branches: ['main']

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Create workflow files for lists in lists.json
        run: |
          for row in $(cat lists.json | jq -r .lists | .[])
          do
             name=$(echo $row | jq -r '.name')
             url=$(echo $row | jq -r '.url')
             cron=$(echo $row | jq -r '.schedule')

             echo $name $url $schedule
          done

