name: Generate, build and publish awesome-go list to Pages

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  generate-and-publish:
    uses: devsjc/awesome-starsorted/.github/workflows/_template.yml@main
    with:
      list-name: awesome-go
      list-url: https://raw.githubusercontent.com/avelino/awesome-go/main/README.md
    secrets: inherit
