name: Generate, build and publish awesome-selfhosted list to Pages

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  generate-and-publish:
    uses: devsjc/awesome-starsorted/.github/workflows/_template.yml@main
    with:
      list-name: awesome-selfhosted
      list-url: https://raw.githubusercontent.com/awesome-selfhosted/awesome-selfhosted/master/README.md
    secrets: inherit
