name: Build, Publish

on:
  push:
    branches: main
  schedule:
    - cron:  '30 3 * * *'
    
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Checkout sort-awesome-lists repo
        run: git clone https://github.com/kvnxiao/sort-awesome-lists
      - name: Build sort-awesome-lists binary
        uses: actions/setup-go@v3
      - run: cd sort-awesome-lists && go build -o sal-cmd main.go
      - name: Parse lists in lists.conf and generate sorted versions
        run: |
          cat lists.conf | while read line || [[ -n $line ]];
          do
             [[ ${line//[[:space:]]/} =~ ^#.* || -z "$line" ]] && continue
             echo $line | tr "=" "\n" | while read -r key; do
             read -r value
               echo "Sorting ${key} at ${value}";
               ./sort-awesome-lists/sal-cmd -t=${{ secrets.GITHUB_TOKEN }} -o=${key}.md ${value}
             done
          done
      - name: Setup Ruby
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: '3.0'
          bundler-cache: true
          cache-version: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
          
  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
