name: Build, Publish

on:
  push:
    branches: main
  schedule:
    - cron:  '30 3 * * *'  
   

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'write'
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Checkout sort-awesome-lists repo
        run: git clone https://github.com/kvnxiao/sort-awesome-lists
      - name: Build sort-awesome-lists
        uses: actions/setup-go@v3
      - run: cd sort-awesome-lists && go build -o sal-cmd main.go
      - name: Build lists
        run: |
          mkdir docs
          cat lists.conf | while read line || [[ -n $line ]];
          do
             [[ ${line//[[:space:]]/} =~ ^#.* || -z "$line" ]] && continue
             echo $line | tr "=" "\n" | while read -r key; do
             read -r value
               echo "Sorting ${key} at ${value}";
               ./sort-awesome-lists/sal-cmd -t=${{ secrets.GITHUB_TOKEN }} -o=docs/${key}.md ${value}
             done
          done
          ls -al docs
